Vagrant.configure("2") do |config|

  # Enable the Puppet provisioner, with will look in manifests
  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = "manifests"
    puppet.manifest_file = "default.pp"
    puppet.module_path = "modules"
  end

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "precise64"

  # Forward guest port 80 to host port 8888 and name mapping
  config.vm.network :private_network, ip: "192.168.56.101"

  config.vm.synced_folder "./..", "/var/www/", :owner => "www-data"

  # insert db
  config.vm.provision "shell", path: "manifests/db.sh"
end
