Application_Model_Category:
    type: entity
    table: category
    id:
        id: 
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
    manyToMany:
        products:
            targetEntity: Application_Model_Product
            mappedBy: categories