Application_Model_Product:
    type: entity
    table: products
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
        description:
            type: string
        price:
            type: decimal
            precision: 6
            scale: 2
    manyToMany:
        categories:
            targetEntity: Application_Model_Category