Application_Model_Product:
    type: entity
    repositoryClass: Application_Model_ProductRepository
    table: products
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
        description:
            type: string
        image:
            type: string
        price:
            type: decimal
            precision: 6
            scale: 2
    manyToMany:
        categories:
            targetEntity: Application_Model_Category
            joinTable:
                name: product_category
                joinColumns:
                    product_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    category_id:
                        referencedColumnName: id